# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'examples/_client.rb'
    - 'examples/_client_i3s.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'lib/oneview-sdk/cli.rb'
    - 'lib/oneview-sdk/resource.rb'

Metrics/LineLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'lib/oneview-sdk/rest.rb'

Style/GlobalVars:
  AllowedVariables: [$config, $secrets, $client, $client_120, $client_300, $client_300_synergy, $config_synergy, $secrets_synergy, $config_i3s, $client_i3s_300, $client_500, $client_500_synergy]

Style/IndentationWidth:
  Width: 2

Style/VariableName:
  EnforcedStyle: snake_case
  Exclude:
    - 'lib/oneview-sdk/resource/**/*'

Style/MethodName:
  Exclude:
    - 'lib/oneview-sdk/resource/**/*'

Style/FileName:
  Exclude:
    - 'lib/oneview-sdk.rb'
    - 'bin/oneview-sdk'

Style/AlignParameters:
  Exclude:
    - 'lib/oneview-sdk/cli.rb'


Style/AccessorMethodName:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Casecmp:
  Enabled: false
