# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'examples/_client.rb'
    - 'examples/_client_i3s.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'lib/oneview-sdk/cli.rb'
    - 'lib/oneview-sdk/resource.rb'

Metrics/LineLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'lib/oneview-sdk/rest.rb'

Metrics/BlockLength:
  Max: 200
  Exclude:
    - 'lib/oneview-sdk/rest.rb'
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$config, $secrets, $client, $client_120, $client_300, $client_300_synergy, $config_synergy, $secrets_synergy, $config_i3s, $client_i3s_300, $client_500, $client_500_synergy, $client_600, $client_600_synergy, $client_800, $client_800_synergy]

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Naming/VariableName:
  EnforcedStyle: snake_case
  Exclude:
    - 'lib/oneview-sdk/resource/**/*'

Naming/VariableNumber:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'lib/oneview-sdk/resource/**/*'

Naming/FileName:
  Exclude:
    - 'lib/oneview-sdk.rb'
    - 'bin/oneview-sdk'

Naming/AccessorMethodName:
  Enabled: false

Layout/AlignParameters:
  Exclude:
    - 'lib/oneview-sdk/cli.rb'

Layout/IndentationWidth:
  Width: 2

Layout/EmptyLines:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentArray:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
